<a href="https://colab.research.google.com/github/sebastian-jarosz/pandas_laboratory/blob/main/Uczenie_Maszynowe_Lab_Cw1_Cw2_Jarosz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
from keras.models import Sequential
from keras.layers import *
import numpy as np
tf.Variable

m = Sequential()
m.add(Dense(2,input_dim=2, activation='tanh'))
m.add(Dense(12,input_dim=2, activation='tanh'))
#m.add(Activation('tanh'))

m.add(Dense(1,activation='sigmoid'))

#m.add(Activation('sigmoid'))

#XOR
X = np.array([[0,0],[0,1],[1,0],[1,1]],'float32')
Y = np.array([[0],[1],[1],[0]],'float32')

m.compile(optimizer='adam',loss='binary_crossentropy')
m.fit(X,Y,batch_size=1,epochs=200,verbose=0)
print(m.predict(X))

[[0.32923204]
 [0.5230524 ]
 [0.70914215]
 [0.5625702 ]]


In [16]:
m = Sequential()
m.add(Dense(2,input_dim=2, activation='tanh'))
m.add(Dense(12,input_dim=2, activation='tanh'))

m.add(Dense(1,activation='sigmoid'))

#OR
X = np.array([[0,0],[0,1],[1,0],[1,1]],'float32')
Y = np.array([[0],[1],[1],[1]],'float32')

m.compile(optimizer='adam',loss='binary_crossentropy')
m.fit(X,Y,batch_size=1,epochs=200,verbose=0)
print(m.predict(X))

[[0.26265013]
 [0.9331873 ]
 [0.91034114]
 [0.9788458 ]]


In [17]:
m = Sequential()
m.add(Dense(2,input_dim=2, activation='tanh'))
m.add(Dense(12,input_dim=2, activation='tanh'))

m.add(Dense(1,activation='sigmoid'))

#NOR
X = np.array([[0,0],[0,1],[1,0],[1,1]],'float32')
Y = np.array([[1],[0],[0],[0]],'float32')

m.compile(optimizer='adam',loss='binary_crossentropy')
m.fit(X,Y,batch_size=1,epochs=200,verbose=0)
print(m.predict(X))

[[0.32966387]
 [0.43171003]
 [0.11717495]
 [0.13074887]]


In [18]:
m = Sequential()
m.add(Dense(2,input_dim=2, activation='tanh'))
m.add(Dense(12,input_dim=2, activation='tanh'))

m.add(Dense(1,activation='sigmoid'))

#AND
X = np.array([[0,0],[0,1],[1,0],[1,1]],'float32')
Y = np.array([[0],[0],[0],[1]],'float32')

m.compile(optimizer='adam',loss='binary_crossentropy')
m.fit(X,Y,batch_size=1,epochs=200,verbose=0)
print(m.predict(X))

[[0.02731916]
 [0.16957343]
 [0.22267503]
 [0.68830115]]


In [19]:
m = Sequential()
m.add(Dense(2,input_dim=2, activation='tanh'))
m.add(Dense(12,input_dim=2, activation='tanh'))

m.add(Dense(1,activation='sigmoid'))

#NAND
X = np.array([[0,0],[0,1],[1,0],[1,1]],'float32')
Y = np.array([[1],[1],[1],[0]],'float32')

m.compile(optimizer='adam',loss='binary_crossentropy')
m.fit(X,Y,batch_size=1,epochs=200,verbose=0)
print(m.predict(X))

[[0.8581939 ]
 [0.5892626 ]
 [0.85360503]
 [0.5641337 ]]


In [ ]:
from keras.models import Sequential
from keras.layers import *
import tensorflow as tf
import numpy as np
tf.Variable

m = Sequential()
m.add(Dense(2,input_dim=2, activation='tanh'))
m.add(Dense(12,input_dim=2, activation='tanh'))
#m.add(Activation('tanh'))

m.add(Dense(1,activation='sigmoid'))

#m.add(Activation('sigmoid'))

X = np.array([[0,0],[0,1],[1,0],[1,1],[1,0],[0,1],[1,1],[0,0]],'float32')
Y = np.array([[0],[1],[1],[0],[1],[0],[1],[1]],'float32')

m.compile(optimizer='adam',loss='binary_crossentropy')
m.fit(X,Y,batch_size=1,epochs=200,verbose=0)
print(m.predict(X))

[[0.555702  ]
 [0.46640384]
 [0.8229134 ]
 [0.6702832 ]
 [0.8229134 ]
 [0.46640384]
 [0.6702832 ]
 [0.555702  ]]


In [ ]:
from keras.models import Sequential
from keras.layers import *
import tensorflow as tf
import numpy as np
tf.Variable

m = Sequential()
m.add(Dense(2,input_dim=2, activation='tanh'))
m.add(Dense(12,input_dim=2, activation='tanh'))
#m.add(Activation('tanh'))

m.add(Dense(1,activation='sigmoid'))

#m.add(Activation('sigmoid'))

X = np.array([[0,0],[0,1],[1,0],[1,1],[1,0],[0,1]],'float32')
Y = np.array([[0],[1],[1],[0],[1],[0]],'float32')

m.compile(optimizer='adam',loss='binary_crossentropy')
m.fit(X,Y,batch_size=1,epochs=200,verbose=0)
print(m.predict(X))

[[0.43738803]
 [0.2332676 ]
 [0.7892575 ]
 [0.37953925]
 [0.7892575 ]
 [0.2332676 ]]
