<a href="https://colab.research.google.com/github/sebastian-jarosz/pandas_laboratory/blob/main/Uczenie_Maszynowe_Lab_Cw1_Cw2_Jarosz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from keras.models import Sequential
from keras.layers import *
import tensorflow as tf
import numpy as np
tf.Variable

m = Sequential()
m.add(Dense(2,input_dim=2, activation='tanh'))
m.add(Dense(12,input_dim=2, activation='tanh'))
#m.add(Activation('tanh'))

m.add(Dense(1,activation='sigmoid'))

#m.add(Activation('sigmoid'))

X = np.array([[0,0],[0,1],[1,0],[1,1]],'float32')
Y = np.array([[0],[1],[1],[0]],'float32')

m.compile(optimizer='adam',loss='binary_crossentropy')
m.fit(X,Y,batch_size=1,epochs=200,verbose=0)
print(m.predict(X))

[[0.47207278]
 [0.5481679 ]
 [0.42728978]
 [0.4668929 ]]


In [3]:
import tensorflow as tf

X1=tf.Variable(initial_value=[0.,1.,0.,1.])
X2=tf.Variable(initial_value=[0.,0.,1.,1.])
Y_AND=tf.Variable(initial_value=[0.,0.,0.,1.])
Y_NOR=tf.Variable(initial_value=[1.,0.,0.,0.])
Y_OR=tf.Variable(initial_value=[0.,1.,1.,1.])
Y_XOR=tf.Variable(initial_value=[0.,1.,1.,0.])
Y_XNOR=tf.Variable(initial_value=[1.,0.,0.,1.])

class Model(object):
 
   def __init__(self):
     # Initialize the weights to `2.0` and the bias to `2.0`
     # In practice, these should be initialized to random values
     # self.W1=tf.random.normal([1])
     self.W1 = tf.Variable(2.)
     self.W2= tf.Variable(2.)
     self.b=tf.Variable(2.)
   
   def __call__(self, x1,x2):
     self.K1=self.W1 * x1 + self.W2 * x2 + self.b
     self.Output = tf.keras.activations.sigmoid(self.K1)
     return(self.Output)
model=Model()

def compute_cost(target_y, predicted_y):
    c=tf.keras.losses.BinaryCrossentropy()
    return(c(target_y,predicted_y))

def None_to_Zero(v):
   if v==None:
      v=0
   return v

def train(model, X1, X2, Y2, learning_rate):
     with tf.GradientTape() as t:
          current_loss = compute_cost(Y2,model(X1,X2))
     dW1,dW2,db=t.gradient(current_loss,[model.W1,model.W2,model.b])          
     dW1=None_to_Zero(dW1)
     db=None_to_Zero(db)
     dW2=None_to_Zero(dW2)
     model.W1.assign_sub(learning_rate * dW1)
     model.b.assign_sub(learning_rate * db)
     model.W2.assign_sub(learning_rate * dW2)

# OR
# As we have very less Input data we need to increase the number of # epochs.
epochs=range(1000)
learning_rate=0.1
for epoch in epochs:
   train(model, X1, X2,Y_OR, learning_rate)
#Once the training is done we can find results by calling the Model  #Class object as 
print(np.round(model(X1, X2).numpy()))

W_OR={'W1': model.W1.numpy(), 'W2': model.W2.numpy(), 'b': model.b.numpy()}

# AND
# As we have very less Input data we need to increase the number of # epochs.
epochs=range(1000)
learning_rate=0.1
for epoch in epochs:
   train(model, X1, X2,Y_AND, learning_rate)
#Once the training is done we can find results by calling the Model  #Class object as 
print(np.round(model(X1, X2).numpy()))

W_AND={'W1': model.W1.numpy(), 'W2': model.W2.numpy(), 'b': model.b.numpy()}

# NOR
# As we have very less Input data we need to increase the number of # epochs.
epochs=range(1000)
learning_rate=0.1
for epoch in epochs:
   train(model, X1, X2,Y_NOR, learning_rate)
#Once the training is done we can find results by calling the Model  #Class object as 
print(np.round(model(X1, X2).numpy()))

W_NOR={'W1': model.W1.numpy(), 'W2': model.W2.numpy(), 'b': model.b.numpy()}

# XOR
class Model_XOR(object):
 
     def __init__(self):
          self.W11 = tf.Variable(W_AND['W1'])
          self.W12= tf.Variable(W_AND['W2'])
          self.b13=tf.Variable(W_AND['b'])
          self.W14 = tf.Variable(W_NOR['W1'])
          self.W15= tf.Variable(W_NOR['W2'])
          self.b16=tf.Variable(W_NOR['b'])
          self.W21 = tf.Variable(W_NOR['W1'])
          self.W22= tf.Variable(W_NOR['W2'])
          self.b23=tf.Variable(W_NOR['b'])

     def __call__(self, x1,x2):
          self.W1=self.W11 * x1 + self.W12*x2 + self.b13
          self.W2=self.W14 * x1 + self.W15*x2 + self.b16
          self.A1 = tf.keras.activations.sigmoid(self.W1)
          self.A2 = tf.keras.activations.sigmoid(self.W2)
          self.W3=self.W21 * self.A1 + self.W22*self.A2 + self.b23
          self.A3 = tf.keras.activations.sigmoid(self.W3)
          return(self.A3)
model_xor=Model_XOR()


def train_xor(model_xor, X1, X2, Y2, learning_rate):
      with tf.GradientTape() as t:
           current_loss = compute_cost(Y2,model_xor(X1,X2))
 
      dW11,dW12,db13,dW14,dW15,db16,dW21,dW22,db23=t.gradient(current_loss,
                                                              [model_xor.W11,model_xor.W12,model_xor.b13,
                                                               model_xor.W14,model_xor.W15,model_xor.b16,
                                                               model_xor.W21,model_xor.W22,model_xor.b23,])
                                                          
      model_xor.W11.assign_sub(learning_rate * None_to_Zero(dW11))
      model_xor.b13.assign_sub(learning_rate * None_to_Zero(db13))
      model_xor.W12.assign_sub(learning_rate * None_to_Zero(dW12))
      model_xor.W14.assign_sub(learning_rate * None_to_Zero(dW14))
      model_xor.b16.assign_sub(learning_rate * None_to_Zero(db16))
      model_xor.W15.assign_sub(learning_rate * None_to_Zero(dW15))
      model_xor.W21.assign_sub(learning_rate * None_to_Zero(dW21))
      model_xor.b23.assign_sub(learning_rate * None_to_Zero(db23))
      model_xor.W22.assign_sub(learning_rate * None_to_Zero(dW22))

epochs=range(100)
learning_rate=0.1
for epoch in epochs:
   train_xor(model_xor, X1, X2,Y_XOR, learning_rate)
   #Once the training is done we can find results by calling the Model_XOR  #Class object as 
print(np.round(model_xor(X1, X2).numpy()))


[0. 1. 1. 1.]
[0. 0. 0. 1.]
[1. 0. 0. 0.]
[0. 1. 1. 0.]


In [6]:
from keras.models import Sequential
from keras.layers import *
import tensorflow as tf
import numpy as np
tf.Variable

m = Sequential()
m.add(Dense(2,input_dim=2, activation='tanh'))
m.add(Dense(12,input_dim=2, activation='tanh'))
#m.add(Activation('tanh'))

m.add(Dense(1,activation='sigmoid'))

#m.add(Activation('sigmoid'))

X = np.array([[0,0],[0,1],[1,0],[1,1],[1,0],[0,1],[1,1],[0,0]],'float32')
Y = np.array([[0],[1],[1],[0],[1],[0],[1],[1]],'float32')

m.compile(optimizer='adam',loss='binary_crossentropy')
m.fit(X,Y,batch_size=1,epochs=200,verbose=0)
print(m.predict(X))

[[0.555702  ]
 [0.46640384]
 [0.8229134 ]
 [0.6702832 ]
 [0.8229134 ]
 [0.46640384]
 [0.6702832 ]
 [0.555702  ]]


In [8]:
from keras.models import Sequential
from keras.layers import *
import tensorflow as tf
import numpy as np
tf.Variable

m = Sequential()
m.add(Dense(2,input_dim=2, activation='tanh'))
m.add(Dense(12,input_dim=2, activation='tanh'))
#m.add(Activation('tanh'))

m.add(Dense(1,activation='sigmoid'))

#m.add(Activation('sigmoid'))

X = np.array([[0,0],[0,1],[1,0],[1,1],[1,0],[0,1]],'float32')
Y = np.array([[0],[1],[1],[0],[1],[0]],'float32')

m.compile(optimizer='adam',loss='binary_crossentropy')
m.fit(X,Y,batch_size=1,epochs=200,verbose=0)
print(m.predict(X))

[[0.43738803]
 [0.2332676 ]
 [0.7892575 ]
 [0.37953925]
 [0.7892575 ]
 [0.2332676 ]]
